// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: ' ',
    appId: '1:806185856011:web:7c3fbd56f915089af46b0e',
    messagingSenderId: '806185856011',
    projectId: 'foodvendorapp-27d12',
    authDomain: 'foodvendorapp-27d12.firebaseapp.com',
    storageBucket: 'foodvendorapp-27d12.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: ' ',
    appId: '1:806185856011:android:3edd6c371833bbeef46b0e',
    messagingSenderId: '806185856011',
    projectId: 'foodvendorapp-27d12',
    storageBucket: 'foodvendorapp-27d12.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: ' ',
    appId: '1:806185856011:ios:c071df0889f85780f46b0e',
    messagingSenderId: '806185856011',
    projectId: 'foodvendorapp-27d12',
    storageBucket: 'foodvendorapp-27d12.firebasestorage.app',
    iosBundleId: 'com.example.foodApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: ' ',
    appId: '1:806185856011:ios:c071df0889f85780f46b0e',
    messagingSenderId: '806185856011',
    projectId: 'foodvendorapp-27d12',
    storageBucket: 'foodvendorapp-27d12.firebasestorage.app',
    iosBundleId: 'com.example.foodApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: ' ',
    appId: '1:806185856011:web:c65e811a9ea326baf46b0e',
    messagingSenderId: '806185856011',
    projectId: 'foodvendorapp-27d12',
    authDomain: 'foodvendorapp-27d12.firebaseapp.com',
    storageBucket: 'foodvendorapp-27d12.firebasestorage.app',
  );
}
